### ISSUE TITLE
metrics not removed on delete_metrics()?

### ISSUE THREAD

**Issue by ioguix** [OPMDG/opm-wh_nagios#2]
According to pgtap tests, it seems wh_nagios.delete_metrics() do not delete metrics from service_counters_* partition.

**Comment by ioguix** [comment]
This appears since 2.5 version.

**Comment by rjuju** [comment]
Thanks for the report!

Actually, the test is wrong, as we're not supposed to drop a partition anymore each time a metric is deleted.  I'll add more tests to validate that data is correctly delete from underlying partition and that the partition is dropped when required.

**Comment by rjuju** [comment]
Fix proposal at https://github.com/OPMDG/opm-wh_nagios/pull/3
